### ISSUE TITLE
About the compositional methods

### ISSUE THREAD

**Issue by gogoczh** [Dongping-Chen/ISG#1]
Great work! I'd like to ask how to implement compositional settings(Gemini-1.5-Pro/Claude-3.5-Sonnet + SD3/SD2.1), for example, what framework did you use. Looking forward to your reply!

**Comment by Dongping-Chen** [comment]
Hi @czhhzc, I've uploaded the script for running compositional settings. Please check the latest readme and simply run `python compositional_inference.py \
    --text_generator <gemini/claude> \
    --image_generator <sd3/sd2.1/flux> \
    --input_file ./ISG_eval/ISG-Bench.jsonl`. This baseline is simple and you can implement your text/image generator within the compositional framework easily.

**Comment by gogoczh** [comment]
Thanks for your reply! It helps me a lot!
